#+TITLE: README
#+AUTHOR: Ryan Devens

* Meta
This repo is not to be modified in anyway by AI tools or automated code generation.

* ABSTRACT
I am putting these together as exercises for myself and others if they so choose.
This repo may be influenced by things I learn using LLMs, and in many other places I will allow carefully reviewed
code generation. But here, in this repo, it is all done by man.

These are supposed to be fundamentals of C++ development that are worth committing to memory.

Focus on fundamentals here.

* BUILDING
Keeping build strategy the same as much as possible.

** Builds done with Makefile and `g++` compiler
- generic / readily available
- justifiable tool to depend on.

* WINDOWS (note)
This will require use of WSL or git bash on windows, (which I do already)
So not messing with that here or other compilers until later.
* DRILLS

** 01_HELLO_WORLD
- running `make` results in /BUILD/hello_world_build to be created
- run `./BUILD/hello_world_build` and notice `hello world` written to cli

** 02_INPUT_AND_LOGIC
- Basic user input using keyboard
- check if prime
- convert to binary

** 03_STRINGS_AND_VECTORS
[[file:DRILLS/03_STRINGS_AND_VECTORS/README.org][README_03_STRINGS_AND_VECTORS]]

** 04_POINTERS_REFS_ARRAYS
[[file:DRILLS/04_POINTERS_REFS_ARRAYS/README.org][README_04_STRINGS_AND_VECTORS]]

** 05_CLASSES_AND_RAII
[[file:DRILLS/05_CLASSES_AND_RAII/README.org][README_05_CLASSES_AND_RAII]]
