xXX := g++
CXXFLAGS := -std=c++17 -Wall -Wextra

build:
	mkdir -p BUILD
	$(CXX) $(CXXFLAGS) -o BUILD/input_and_logic_build SOURCE/main.cpp SOURCE/Logic.cpp

test:
	mkdir -p TESTS
	$(CXX) $(CXXFLAGS) -o TESTS/input_and_logic_tests_build TESTS/test_main.cpp SOURCE/main.cpp SOURCE/Logic.cpp
	./TESTS/input_and_logic_tests_build

clean:
	rm -f BUILD/input_and_logic_build TESTS/input_and_logic_tests_build
